"""remove_unique_constraint_from_patient_email

Revision ID: 0219813dd083
Revises: 34a6d211585e
Create Date: 2026-03-07 20:34:15.590283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0219813dd083'
down_revision: Union[str, None] = '34a6d211585e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_email', table_name='patients')
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.create_index('ix_patients_email', 'patients', ['email'], unique=True)
    # ### end Alembic commands ###
