"""add_status_to_provider_time_off

Revision ID: 3103ac138841
Revises: 3c7f85b13027
Create Date: 2026-04-04 13:17:59.215760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3103ac138841'
down_revision: Union[str, None] = '3c7f85b13027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable first
    op.add_column('provider_time_off', sa.Column('status', sa.String(length=20), nullable=True))
    
    # 2. Update existing data
    op.execute("UPDATE provider_time_off SET status = 'approved' WHERE is_approved = TRUE")
    op.execute("UPDATE provider_time_off SET status = 'pending' WHERE is_approved = FALSE OR is_approved IS NULL")
    
    # 3. Alter to NOT NULL
    op.alter_column('provider_time_off', 'status', nullable=False)
    
    op.add_column('provider_time_off', sa.Column('rejected_by', sa.String(length=36), nullable=True))
    op.add_column('provider_time_off', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('provider_time_off', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'provider_time_off', 'users', ['rejected_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider_time_off', type_='foreignkey')
    op.drop_column('provider_time_off', 'reviewed_at')
    op.drop_column('provider_time_off', 'rejection_reason')
    op.drop_column('provider_time_off', 'rejected_by')
    op.drop_column('provider_time_off', 'status')
    # ### end Alembic commands ###
