"""Add SoftDeleteMixin to Provider model

Revision ID: cd3288837ce9
Revises: 3103ac138841
Create Date: 2026-04-05 14:23:32.075276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3288837ce9'
down_revision: Union[str, None] = '3103ac138841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('providers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_providers_is_active'), 'providers', ['is_active'], unique=False)
    op.add_column('waitlist', sa.Column('assignment_method', sa.String(length=20), nullable=True))
    op.drop_index('ix_waitlist_queue_order', table_name='waitlist')
    op.create_index('ix_waitlist_queue_order', 'waitlist', ['status', 'priority', 'queue_position', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_queue_order', table_name='waitlist')
    op.create_index('ix_waitlist_queue_order', 'waitlist', ['status', 'priority', 'created_at'], unique=False)
    op.drop_column('waitlist', 'assignment_method')
    op.drop_index(op.f('ix_providers_is_active'), table_name='providers')
    op.drop_column('providers', 'deleted_at')
    op.drop_column('providers', 'is_active')
    # ### end Alembic commands ###
